### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by rogierlommers**

### CODE REVIEW

**Comment by veggiemonk** [comment]
@drichard this should be merged please

**Comment by rogierlommers** [comment]
I see I have a typo in the readme, it should be:

`docker run -p 8080:80 rogierlommers/mindmaps`

**Comment by alexanderadam** [comment]
It would be nice if there would be an _official_ [automated build on Docker hub](https://docs.docker.com/docker-hub/builds/) after this is merged (and a reference from the README).

**Comment by drichard** [comment]
Closing this because I never followed up on it and it's probably outdated by now.

**Pull request closed without merging**
